# Site settings
title: DataShiz
email: you@example.com
description: > # this means to ignore newlines until "baseurl:"
  data and shiz.
baseurl:  /datashiz
url:  http://christophershane.github.io/datashiz
twitter_username: twitter_username
github_username:  github_username

# Build settings
markdown: kramdown

gems: [jekyll-paginate]
highlighter: pygments

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  viz:
    output: true
    permalink: /viz/:path/
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: true
    permalink: /poetry/:path/


